apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: books-api
  description: An API for managing books
  tags:
    - openapi-ref
spec:
  type: openapi
  lifecycle: experimental
  definition:
    $openapi: ./books-api.yaml
