apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: books-openapi
  description: An API for managing books
  tags:
    - ref
spec:
  type: openapi
  lifecycle: experimental
  owner: some-team
  definition:
    $openapi: ./books-api.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: books-asyncapi
  description: Book events
  tags:
    - ref
spec:
  type: asyncapi
  lifecycle: experimental
  owner: some-team
  definition:
    $asyncapi: ./books-asyncapi.yaml
    
